name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Deploy to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}
          app_name: modul-1-coding-standards
          service_name: web